version: 2

default_steps: &default_steps
  steps:
    - checkout

    # System
    - run:
        name: Install system dependencies
        command: |
          sudo apt update -yq
          if [[ $USE_MCRYPT = 'true' ]]; then
            sudo apt install libmcrypt-dev -yq;
            sudo docker-php-ext-install -j$(nproc) mcrypt;
          fi

    # Composer
    - run:
        name: Run Composer
        command: |
          if [[ $SETUP = 'stable' ]]; then COMPOSER_MEMORY_LIMIT=-1 composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
          if [[ $SETUP = 'lowest' ]]; then COMPOSER_MEMORY_LIMIT=-1 composer update --prefer-dist --no-interaction --prefer-stable --no-suggest --prefer-lowest; fi

    # Tests
    - run:
        name: Run tests
        command: |
          mkdir -p tests/phpunit
          vendor/bin/phpunit --coverage-clover tests/coverage_clover.xml --log-junit tests/phpunit/junit.xml
          php vendor/bin/codacycoverage clover tests/coverage_clover.xml
    - store_test_results:
        path: tests/phpunit

jobs:
  php-5.6:
    docker:
      - image: circleci/php:5.6
    environment:
      SETUP: stable
      USE_MCRYPT: true

    <<: *default_steps

  php-5.6-lowest:
    docker:
      - image: circleci/php:5.6
    environment:
      SETUP: lowest
      USE_MCRYPT: true

    <<: *default_steps

  php-7.0:
    docker:
      - image: circleci/php:7.0
    environment:
      SETUP: stable
      USE_MCRYPT: true

    <<: *default_steps

  php-7.0-lowest:
    docker:
      - image: circleci/php:7.0
    environment:
      SETUP: lowest
      USE_MCRYPT: true

    <<: *default_steps

  php-7.1:
    docker:
      - image: circleci/php:7.1
    environment:
      SETUP: stable
      USE_MCRYPT: false

    <<: *default_steps

  php-7.1-lowest:
    docker:
      - image: circleci/php:7.1
    environment:
      SETUP: lowest
      USE_MCRYPT: false

    <<: *default_steps

  php-7.2:
    docker:
      - image: circleci/php:7.2
    environment:
      SETUP: stable
      USE_MCRYPT: false

    <<: *default_steps

  php-7.2-lowest:
    docker:
      - image: circleci/php:7.2
    environment:
      SETUP: lowest
      USE_MCRYPT: false

    <<: *default_steps

  php-7.3:
    docker:
      - image: circleci/php:7.3
    environment:
      SETUP: lowest
      USE_MCRYPT: false

    <<: *default_steps

  php-7.3-lowest:
    docker:
      - image: circleci/php:7.3
    environment:
      SETUP: lowest
      USE_MCRYPT: false

    <<: *default_steps

  php-7.4:
    docker:
      - image: circleci/php:7.4
    environment:
      SETUP: lowest
      USE_MCRYPT: false

    <<: *default_steps

  php-7.4-lowest:
    docker:
      - image: circleci/php:7.4
    environment:
      SETUP: lowest
      USE_MCRYPT: false

    <<: *default_steps

workflows:
  version: 2
  build:
    jobs:
      - php-5.6
      - php-5.6-lowest
      - php-7.0
      - php-7.0-lowest
      - php-7.1
      - php-7.1-lowest
      - php-7.2
      - php-7.2-lowest
      - php-7.3
      - php-7.3-lowest
      - php-7.4
      - php-7.4-lowest
